lojistic/config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: [:index, :show, :new, :create, :destroy]
  root 'reports#index'
  post '/reports/preview', to: 'reports#preview'
end

lojistic/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lojistic/app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :packages

  INVOICE_TYPES = ['Fedex', 'UPS', 'Maersk', 'Hapag-Lloyd', 'COSCO']

  validates :invoice_type, :date, :amount, :reference_number, presence: true
  validates :invoice_type, inclusion: INVOICE_TYPES

  scope :created_between, -> (begin_date, end_date) {where(date: begin_date..end_date)}

  def num_unique_services
    self.packages.map(&:service_name).uniq.count
  end
end

lojistic/app/models/package.rb
class Package < ApplicationRecord
  belongs_to :invoice

  SERVICE_NAMES = ['Amazon', 'eBay', 'Etsy', 'Shopify', 'Walmart']

  validates :tracking_number, :service_name, presence: true
  validates :service_name, inclusion: SERVICE_NAMES
end

lojistic/app/models/report.rb
class Report < ApplicationRecord
  attribute :deleted, default: :false
  REPORT_TYPES = ['InvoiceSummary']

  validates :report_type, :start_date, :end_date, presence: true
  validates :report_type, inclusion: REPORT_TYPES
  validates_with ReportDatesValidator

  has_one_attached :csv_report
  
  def soft_delete
    self.update(:deleted => true) 
  end

  def invoice_list
    Invoice.created_between(self.start_date, self.end_date).order(:date)
  end

  def self.preview(begin_date, end_date)
    Invoice.created_between(begin_date, end_date).order(:date).take(50)
  end

end

lojistic/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lojistic/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
  def index
    @reports = Report.where(:deleted => :false).all
  end

  def show
    @report = Report.find params[:id]
  end

  def new
    @report = Report.new
  end

  def preview
    @report = Report.new(report_params)
    if @report.valid?
      @invoices = Report.preview(@report.start_date, @report.end_date)
    else
      render 'new'
    end
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      flash[:notice] = "Report was successfully created. Currently being generated."
      InvoiceSummaryReportCreateJob.perform_later(@report)
      redirect_to reports_path
    else
      render 'new'
    end
  end

  def destroy
    @report = Report.find params[:id]
    @report.soft_delete
    flash[:notice] = "Report was successfully deleted."
    redirect_to reports_path
  end


  private

  def report_params
    params.require(:report).permit(:report_type, :start_date, :end_date)
  end

end

lojistic/app/helpers/application_helper.rb
module ApplicationHelper
end

lojistic/app/helpers/reports_helper.rb
module ReportsHelper
  def download_link(report)
    if report.csv_report.attachment
      link_to report.csv_report.filename, 
        rails_blob_url(report.csv_report, disposition: 'attachment')
    else
      'Report pending creation.'
    end
  end
end

lojistic/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lojistic
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %h1 Lojistic
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    = yield

lojistic/app/views/reports/index.html.haml
%h2 Reports List

%table#reports-list
  %thead
    %tr
      %th Type
      %th Start Date
      %th End Date
      %th Download
      %th Delete
  %tbody
    - @reports.each do |report|
      %tr
        %td 
          = link_to "#{report.report_type}", report_path(report)
        %td #{report.start_date}
        %td #{report.end_date}
        %td 
          = download_link(report)
        %td 
          = link_to 'Delete', report_path(report), :method => :delete, 
              :data => {:confirm => 'Are you sure?'}

= link_to 'Add New Report', new_report_path

lojistic/app/views/reports/new.html.haml
%h2 Create New Report

- unless @report.errors.empty?
  #warning
    Errors prevented this report from being created.
    %ul
      - @report.errors.full_messages.each do |error|
        %li= error

= form_for(Report.create) do |f|

  %label{:for => :report_type} Report Type
  = f.select :report_type, Report::REPORT_TYPES
  %br

  %label{:for => :start_date} Start Date
  = f.date_field :start_date
  %br

  %label{:for => :end_date} End Date
  = f.date_field :end_date
  %br
  
  = hidden_field_tag :authenticity_token, form_authenticity_token

  = f.submit 'Preview', formaction: 'preview'
  %br

  = f.submit

lojistic/app/views/reports/preview.html.haml
%h2 Report Preview

%table#invoices-list
  %thead
    %tr
      %th Invoice Type
      %th Invoice Date
      %th Invoice Amount
      %th Invoice Reference Number
      %th Number of Packages
      %th Unique Service Names
  %tbody
    - @invoices.each do |invoice|
      %tr
        %td #{invoice.invoice_type}
        %td #{invoice.date}
        %td #{invoice.amount}
        %td #{invoice.reference_number}
        %td #{invoice.packages.count}
        %td #{invoice.num_unique_services}

lojistic/app/views/reports/show.html.haml
%h2 Report Detail

%ul#report-details
  %li
    Report Type:
    = @report.report_type
  %li
    Start Date:
    = @report.start_date
  %li
    End Date:
    = @report.end_date